#!/bin/bash

echo ''
echo '0) make sure you have dependencies'
echo '   $ sudo bootstrap/ubuntu-dependencies.sh'
echo ''
echo '1) make sure dotfiles are linked'
echo '   $ bootstrap/dotfiles.sh'
echo ''
echo '2) bootstrap vim'
echo '   $ bootstrap/vim.sh'
echo ''
echo '3) init rbenv and associated tools'
echo '   $ bootstrap/tools-rbenv.sh'
echo ''
echo '4) init pyenv and associated tools'
echo '   $ bootstrap/tools-pyenv.sh'
echo ''
echo '5) party'
echo ''
