---
- hosts: all
  sudo: true
  tasks:
    - name:       update apt cache
      apt:        update_cache=yes
    - name:       install required packages
      apt:        name={{ item }} state=present
      with_items:
        - git
        - silversearcher-ag
        - vim
        - tmux
