#!/bin/bash

export VISUAL=vim
export EDITOR="$VISUAL"

# if [ "$color_prompt" = yes ]; then
#     PS1='\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\n\$ '
# else
#     PS1='\u@\h:\w\n\$ '
# fi

# PS1='\u@\h:\w\n\$ '
PS1='\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\n\$ '

# color aliases
alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# sensible.bash
source $HOME/.sensible.bash

# aliases
if [ -f ~/.bash_aliases ]; then
	. ~/.bash_aliases
fi

# functions
if [ -f ~/.bash_functions ]; then
	. ~/.bash_functions
fi

# applications (e.g. rbenv setup)
if [ -f ~/.bash_applications ]; then
	. ~/.bash_applications
fi

# any local bashery
if [ -f ~/.bash_stuff.local ]; then
	. ~/.bash_stuff.local
fi

# force_color_prompt=yes

# # set a fancy prompt (non-color, unless we know we "want" color)
# case "$TERM" in
#     xterm-color) color_prompt=yes;;
# esac

# if [ -n "$force_color_prompt" ]; then
#     if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
# 	color_prompt=yes
#     else
# 	color_prompt=
#     fi
# fi



# # enable color support of ls
# # with solarized colors (final step)
# if [ -x /usr/bin/dircolors ]; then
#     test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
#     alias ls='ls --color=auto'
#     #alias dir='dir --color=auto'
#     #alias vdir='vdir --color=auto'

#     alias grep='grep --color=auto'
#     alias fgrep='fgrep --color=auto'
#     alias egrep='egrep --color=auto'
# fi
