#!/bin/bash
# applications that can/should be configured/registered with the shell

# rbenv
if [ -d "$HOME/.rbenv" ]; then
  export PATH="$PATH:$HOME/.rbenv/bin"
fi

# pyenv
if [ -d "$HOME/.pyenv" ]; then
  export PATH="$PATH:$HOME/.pyenv/bin"
fi

# init rbenv stuff
if program_exists rbenv; then
  eval "$(rbenv init -)"
fi

# init pyenv stuff
if program_exists pyenv; then
  eval "$(pyenv init -)"
fi

# can initialize stuff that depends on rbenv or pyenv

if program_exists teamocil; then
  complete -W "$(teamocil --list)" teamocil
fi
