#!/bin/bash
# applications that need to be configured/registered with the shell by default

# rbenv
# pyenv
export PATH="$HOME/.rbenv/bin:$HOME/.pyenv/bin:$PATH"

# init rbenv stuff
eval "$(rbenv init -)"

# init pyenv stuff
eval "$(pyenv init -)"

# now we can initialize stuff that depends on rbenv or pyenv
complete -W "$(teamocil --list)" teamocil
