#!/bin/bash
# applications that need to be configured/registered with the shell by default

# rbenv
# pyenv
export PATH="$HOME/.rbenv/bin:$HOME/.pyenv/bin:$PATH"

eval "$(rbenv init -)"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
