#!/bin/bash

alias up='cd ..'

alias tmxnew='tmux new-session -s'
alias tmxcon='tmux attach -t'
alias tmxls='tmux ls'

# git
#  short rev hash
alias gver='git rev-parse --short HEAD'
#  status
alias gst='git status'
#  logs
alias gl='git log --topo-order --pretty=format:"%Cred%h%Creset >> %Cgreen%ar%Creset%n -%C(yellow)%d%Creset %s %Cblue<%an>%Creset"'
alias glo='git log --topo-order --pretty=format:"%Cred%h%Creset %C(yellow)%d%Creset \"%s\" %Cgreen%ar%Creset %Cblue<%an>%Creset"'
alias glg='git log --topo-order --all --graph --pretty=format:"%Cred%h%Creset >> %ar%n -%C(yellow)%d%Creset %s <%an>"'

#  commit
alias gaam='git commit -a --amend --no-edit'
alias gcm='git commit --message'
alias gcam='git commit -a --message'
#  branch
alias gco='git checkout'
alias gcom='git checkout master'
alias gbr='git branch'
alias glast='git log -n 1 -p'

# Ambient engine noise
# requires package sox
# http://www.reddit.com/r/commandline/comments/29le5u/generate_your_own_ambient_tng_enterprise_engine/
# alias warp="play -c 2 -n -c1 synth whitenoise lowpass -1 120 lowpass -1 120 lowpass -1 120 gain +10"

# Pomodoro timer daemon with thyme
# alias startpom="thyme && thyme -b"

# Matrix
alias matrix='cmatrix -abs' # closes with a key

# calendar with todays date
# alias tcal='cal | grep --before-context 6 --after-context 6 --color -e " $(date +%e) " -e "^$(date +%e)"'

# calendar with this week's date
# alias tweek='cal | grep --color -e " $(date +%e) " -e "^(date +%e)"'


