#!/bin/bash
# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)

# aliases
if [ -f ~/.bash_aliases ]; then
	. ~/.bash_aliases
fi

# functions
if [ -f ~/.bash_functions ]; then
	. ~/.bash_functions
fi

# applications (e.g. rbenv setup)
if [ -f ~/.bash_applications ]; then
	. ~/.bash_applications
fi

# any local bashery
if [ -f ~/.bash_stuff.local ]; then
	. ~/.bash_stuff.local
fi

## If not running interactively, don't do anything
#case $- in
    #*i*) ;;
      #*) return;;
#esac

force_color_prompt=yes

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color) color_prompt=yes;;
esac

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
	color_prompt=yes
    else
	color_prompt=
    fi
fi

#http://ethanschoonover.com/solarized
#base03:    #002b36
#base02:    #073642
#base01:    #586e75
#base00:    #657b83
#base0:     #839496
#base1:     #93a1a1
#base2:     #eee8d5
#base3:     #fdf6e3
#yellow:    #b58900
#orange:    #cb4b16
#red:       #dc322f
#magenta:   #d33682
#violet:    #6c71c4
#blue:      #268bd2
#cyan:      #2aa198
#green:     #859900
if [ "$color_prompt" = yes ]; then
    PS1='\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\n\$ '
else
    PS1='\u@\h:\w\n\$ '
fi


# enable color support of ls
# with solarized colors (final step)
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# Update window size after every command
shopt -s checkwinsize

## SANE HISTORY DEFAULTS ##

# Append to the history file, don't overwrite it
shopt -s histappend

# Save multi-line commands as one command
shopt -s cmdhist

# Record each line as it gets issued
PROMPT_COMMAND='history -a'

# Huge history. Doesn't appear to slow things down, so why not?
HISTSIZE=500000
HISTFILESIZE=100000

# Avoid duplicate entries
HISTCONTROL="erasedups:ignoreboth"

# Don't record some commands
export HISTIGNORE="&:[ ]*:exit:ls:bg:fg:history:clear"

# Use standard ISO 8601 timestamp
# %F equivalent to %Y-%m-%d
# %T equivalent to %H:%M:%S (24-hours format)
HISTTIMEFORMAT='%F %T '

## BETTER DIRECTORY NAVIGATION ##

# Prepend cd to directory names automatically
shopt -s autocd 2> /dev/null
# Correct spelling errors during tab-completion
shopt -s dirspell 2> /dev/null
# Correct spelling errors in arguments supplied to cd
shopt -s cdspell 2> /dev/null

# This allows you to bookmark your favorite places across the file system
# Define a variable containing a path and you will be able to cd into it regardless of the directory you're in
shopt -s cdable_vars

# Examples:
export dotfiles="$HOME/dotfiles"
export projects="$HOME/projects"
export hacking="$HOME/hacking"

# some stuff borrowed from
# https://github.com/mrzool/bash-sensible/blob/master/sensible.bash
