#!/bin/bash

# borrowed from
# https://github.com/tscheffe/dotfiles/blob/master/bootstrap/apps.sh
program_exists() {
  type $1 > /dev/null 2>&1
}

# borrowed from
# https://github.com/tscheffe/dotfiles/blob/master/bootstrap/apps.sh
ensure_exists() {
  if [[ ! -d $1 ]]; then
    echo "creating ${1}"
    mkdir $1
  fi
}

function show_colors() {
  for fgbg in 38 48 ; do #Foreground/Background
    for color in {0..256} ; do #Colors
      #Display the color
      echo -en "\e[${fgbg};5;${color}m ${color}\t\e[0m"
      #Display 10 colors per lines
      if [ $((($color + 1) % 10)) == 0 ] ; then
        echo #New line
      fi
    done
    echo #New line
  done
}
