#!/bin/bash

# borrowed from
# https://github.com/tscheffe/dotfiles/blob/master/bootstrap/apps.sh
program_exists() {
  type $1 > /dev/null 2>&1
}

# borrowed from
# https://github.com/tscheffe/dotfiles/blob/master/bootstrap/apps.sh
ensure_exists() {
  if [[ ! -d $1 ]]; then
    echo "creating ${1}"
    mkdir $1
  fi
}
