#!/bin/bash

# clear the known keys record for ssh into localhost
# this happens with vagrant
clear_known_host_keys_for_localhost() {
  echo 'clearing known_hosts for 127.0.0.1 and localhost'
  echo '... port 2222'
  ssh-keygen -f "/home/nemanja/.ssh/known_hosts" -R [127.0.0.1]:2222
  ssh-keygen -f "/home/nemanja/.ssh/known_hosts" -R [localhost]:2222
}

# borrowed from
# https://github.com/tscheffe/dotfiles/blob/master/bootstrap/apps.sh
program_exists() {
  type $1 > /dev/null 2>&1
}

# borrowed from
# https://github.com/tscheffe/dotfiles/blob/master/bootstrap/apps.sh
ensure_exists() {
  if [[ ! -d $1 ]]; then
    echo "creating ${1}"
    mkdir $1
  fi
}
